[workspace]
resolver = "2"
members = [
    "surrealdb_extra",
    "surrealdb_extra_derive",
    "surrealdb_extra_tests",
    "surrealdb_extra_bench",
]

[workspace.dependencies]
surrealdb = "2.0.1"

[workspace.package]
version = "0.9.0"
edition = "2021"
rust-version = "1.79.0"
